Resource Link: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


In [ ]:
#!nvidia-smi

# Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

---

* Scalar (Rank 0 Tensor): A scalar is a single number. In PyTorch, you create a scalar by passing a single value to torch.tensor(). The code creates a scalar with a value of 7. .ndim checks the number of dimensions (which is 0 for a scalar), .shape returns an empty tuple since scalars have no dimensions, and .item() converts the tensor scalar to a standard Python scalar.

* Vector (Rank 1 Tensor): A vector is a 1-dimensional array of numbers. The code creates a vector [7, 7] using torch.tensor(). Here, .ndim returns 1 indicating it's 1-dimensional, and .shape returns (2), meaning the vector has 2 elements.

* Matrix (Rank 2 Tensor): A matrix is a 2-dimensional array of numbers. The example creates a 2x2 matrix with torch.tensor([[7, 8], [9, 10]]). .ndim shows it's 2-dimensional, and .shape returns (2, 2), indicating 2 rows and 2 columns.

* Higher-Dimensional Tensor (Rank 3+ Tensor): Tensors can have three or more dimensions. The provided code creates a tensor with dimensions (1, 3, 3), meaning it contains a 3x3 matrix in a 3-dimensional space. .ndim confirms it's 3-dimensional. The shape is described as having 1 matrix that contains 3 rows and 3 columns each.

This code is a basic introduction to the concept of tensors in PyTorch, demonstrating how to create them and inspect their properties like dimensionality and shape. Understanding these properties is essential for working with data in machine learning and deep learning applications.

---

**Naming Conventions**
* Scalar (dimension = 0) - lower-case $a$
* Vector (dimension = 1) - lower-case $y$
* Matrix (dimension = 2) - upper-case $Q$
* Tensor (dimension ≥ 3) - upper-case $X$

In [3]:
# Scalar (tensor rank 0)
scalar = torch.tensor(7) # A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor

print(scalar)
print(scalar.ndim) # checks how many dimensions does scalar have
print(scalar.shape)
print(scalar.item()) # Get tensor back as Python int


tensor(7)
0
torch.Size([])
7


> The .item() method is specific to tensors that have a single element. Its purpose is to extract the value of that single element as a standard Python number (int or float). It's particularly useful when you're working with tensors that result from some computations, and you want to convert the result into a Python scalar.

> Attempting to use .item() on a tensor with more than one element will result in an error because it's not clear which element should be converted to a Python scalar. The method is designed to ensure that it's only used when there's exactly one element in the tensor, thereby avoiding ambiguous situations.

In [4]:
# Vector (tensor rank 1)
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim) # checks how many dimension does vector have
print(vector.shape) # outputs the shape of the vector, eg 2 by 1.

tensor([7, 7])
1
torch.Size([2])


In [5]:
# Matrix (tensor rank 2)
MATRIX = torch.tensor([[7, 8], [9, 10]])
print(MATRIX)
print(MATRIX.ndim) # checks how many dimension does MATRIX have
print(MATRIX.shape) # outputs the shape of the matrix

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [6]:
# Tensor (tensor rank 3+)
TENSOR = torch.tensor([[[1, 2, 3],   #[ <-- dim=0[ <-- dim=1 [ <-- dim=2 ]]]
                        [4, 5, 6],
                        [6, 7, 8]]])
print(TENSOR)
print(TENSOR.ndim) # checks how many dimension does TENSOR have

print(TENSOR.shape) # outputs the shape of the tensor
                    # torch.Size([1, 3, 3]) means that you have 1x 3 by 3 matrix in this tensor.
                    # torch.Size([dim=0, dim=1, dim=2])
                    # alternatively, dim=0 contains 1 value (matrix), dim=1 contains 3 values (vector), dim=2 contains 3 scalars each.


tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])
3
torch.Size([1, 3, 3])


### Random Tensors

**Why random tensors?**

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Workflow:

> `Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

PyTorch Docs (torch.rand()) url - https://pytorch.org/docs/stable/generated/torch.rand.html


In [11]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.7914, 0.5113, 0.5421, 0.4303],
        [0.0433, 0.1506, 0.8021, 0.9484],
        [0.7071, 0.0527, 0.7459, 0.5756]])


###Miscellaneous Notes - Image Tensor ()

**GPT Prompt:** In tensor-speak (the language used to describe tensors), the tensor would have three dimensions, one for colour_channels, height and width.

<br>

**GPT Answer:**

The quote you've provided talks about how to describe the structure of a tensor, particularly in the context of image data, using the specific terminology or "language" associated with tensors.

In the realm of machine learning and computer vision, images are commonly represented as tensors. A tensor, in this context, is essentially a multi-dimensional array. For an image, these dimensions correspond to different aspects of the data it contains:

Color Channels: The number of channels in an image represents the depth of color information. For instance, a standard RGB (Red, Green, Blue) image has three color channels. Each channel stores intensity values for its respective color across the image. There are also grayscale images, which have just one channel, and other formats that may have more channels (like RGBA, where the A stands for Alpha or transparency).

Height: This dimension represents the vertical size of the image in pixels.

Width: This dimension represents the horizontal size of the image in pixels.

So, when the quote mentions a tensor having "three dimensions, one for color_channels, height, and width," it's describing how an image is structured in a way that's understood by tensor operations. For a color image in the RGB format, you could conceptualize it as a 3D tensor:

The first dimension corresponds to the color channels (3 for RGB).
The second dimension corresponds to the height of the image in pixels.
The third dimension corresponds to the width of the image in pixels.
Thus, if you have a 1080x1920 pixel RGB image, in tensor-speak, you would describe it as having dimensions of 3x1080x1920, where 3 represents the RGB channels, 1080 represents the height, and 1920 represents the width.

Understanding this terminology is crucial for working with image data in machine learning frameworks like TensorFlow or PyTorch, as it affects how you process, manipulate, and train models with image data.

<br>
---
<br>

Here's an example of what a tensor array for a 10x10 image with RGBA channels might look like. Each entry in this array is a randomly generated integer between 0 and 255, representing the intensity of the Red, Green, Blue, and Alpha (transparency) channels at each pixel:

---
```
Array shape: (4, 10, 10)

array([[[203, 178,  63, 203,  19,  80,  77,  99, 226, 227], #red
        [148,  31, 141, 150, 187, 184, 214,  10,  40,  95],
        [ 96,  76, 213, 117,  79, 224, 174,  44,   7, 236],
        [182,  25, 242, 120, 207, 194,  52,  38,  42, 222],
        [105, 193, 169, 146, 221,  76, 179,  84, 109, 222],
        [  4, 105,  73,  54, 242, 172, 238,  23,  89, 192],
        [ 79,  26,  75, 133,  92,  10, 115, 114,  87, 227],
        [124, 183,  36, 176, 115, 246, 151, 227,  54,   1],
        [  8, 255, 102, 242, 116,  93,  10, 184, 184,   1],
        [161, 118,  98, 150,  89, 208,  76,  77,  58, 136]],

       [[171, 231, 224, 128, 149, 101,  72, 167,  57, 178], #green
        [170,   3, 175, 194, 243,  77, 188,  97, 197, 206],
        [250, 197,  22, 191, 215, 156,  73,  38, 196,  34],
        [255, 164, 187,  28, 114, 140,  65, 162,  74, 168],
        [212, 127, 120, 162,  86,  22, 141, 126,  81, 167],
        [168, 201,  21, 219, 148,  70, 102, 206, 111, 214],
        [ 23, 204, 152,  56, 164, 110, 197, 213,  28, 206],
        [162, 149, 100, 206,  25,  88, 161,  83, 173, 177],
        [218,  38,  76, 220,  37,  36,  11, 228,   0, 107],
        [ 29,  94, 173, 170,  31, 207, 251,  65, 205,  95]],

       [[ 17, 117, 145,  64, 124,  20, 242, 202, 159,  72], #blue
        [214, 102, 124, 170, 191,  93,  23, 251, 249,  62],
        [ 25, 245, 169, 116, 131,  39,  68, 147,  79,  90],
        [111,  33,  35, 196, 197, 170,  51, 197,  62,  70],
        [ 47,  41, 113, 166, 202,  24, 242, 246,  68, 245],
        [174,   4,  77,  83,  42,  65, 183,  58, 113,  44],
        [221, 117, 252, 153, 119,  45, 137, 104,  58,  57],
        [168, 231, 210, 239,  32,  30,   9, 150,  95, 214],
        [127, 240,  56, 200, 161, 137, 197,   6, 231,  72],
        [  4, 109,  53,  11, 197, 217,  88,   1, 249, 254]],

       [[ 23, 252, 127,   8,  58, 222, 123,   6,  14, 108], #alpha
        [  4, 195,  26, 177,  59, 145, 199, 167, 181,  93],
        [  4, 119, 204, 182, 108,  53, 175, 159,  83,  50],
        [ 47, 233, 103, 198,  84, 134,  42, 145,  93, 235],
        [ 35, 165, 152,  77, 101, 153, 242, 206, 109,   9],
        [ 78, 210, 182, 151,  48, 209, 199,  33, 138,  95],
        [226, 206, 106,  47,  54,  49, 178, 107, 112, 105],
        [195,  17,  24, 144,  91,  14, 102, 123, 246, 231],
        [253, 137,  22, 133,  19, 192, 166,  24, 145,  78],
        [ 69, 165, 135, 255, 122, 125, 135, 160, 174,  54]]], dtype=uint8)
```
---

This representation shows a 4-dimensional tensor where:

* The first dimension corresponds to the color channels (RGBA), so there are 4 layers or slices.
* The second and third dimensions correspond to the height and width of the image, respectively, both set to 10 pixels in this example.

Each "layer" or slice of the tensor represents one of the RGBA channels across the entire image. The values within each layer represent the intensity of that channel for each pixel, with 0 being no intensity (or completely transparent for the alpha channel) and 255 being the maximum intensity. ​​






In Jupyter notebooks, which include Google Colab notebooks, you do not always need to use the print() function to display output. This environment is designed for interactive computing, and it has a feature that automatically displays the result of the last operation in each cell.

When you run a cell in a Jupyter notebook (or Google Colab, which is based on Jupyter), the following rules apply:

The last line of code in a cell, when executed, will have its result displayed below the cell, even if it is not printed with the print() function. This is known as the cell's output.
If the last line of code does not produce any output, nothing is displayed.
If you have other lines of code in the cell whose output you wish to display, you need to explicitly use print() or another display function for those lines.
This feature is especially useful for quick data exploration and analysis, as it allows you to see the results immediately without needing to use print() every time. However, if you want to format the output or display multiple outputs within a cell, you'll need to use print() or another suitable display function.

**Notes Regarding Why you don't need to declare print() to output value in Google Colab**

<br>

In Jupyter notebooks, which include Google Colab notebooks, you do not always need to use the $print()$ function to display output. This environment is designed for interactive computing, and it has a feature that automatically displays the result of the last operation in each cell.

When you run a cell in a Jupyter notebook (or Google Colab, which is based on Jupyter), the following rules apply:

1. The last line of code in a cell, when executed, will have its result displayed below the cell, even if it is not printed with the $print()$ function. This is known as the cell's output.
2. If the last line of code does not produce any output, nothing is displayed.
3. If you have other lines of code in the cell whose output you wish to display, you need to explicitly use $print()$ or another display function for those lines.


This feature is especially useful for quick data exploration and analysis, as it allows you to see the results immediately without needing to use $print()$ every time. However, if you want to format the output or display multiple outputs within a cell, you'll need to use $print()$ or another suitable display function.