Resource Link: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


In [2]:
#!nvidia-smi

# Introduction to Tensors




### Creating Tensors




PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

---

* Scalar (Rank 0 Tensor): A scalar is a single number. In PyTorch, you create a scalar by passing a single value to torch.tensor(). The code creates a scalar with a value of 7. .ndim checks the number of dimensions (which is 0 for a scalar), .shape returns an empty tuple since scalars have no dimensions, and .item() converts the tensor scalar to a standard Python scalar.

* Vector (Rank 1 Tensor): A vector is a 1-dimensional array of numbers. The code creates a vector [7, 7] using torch.tensor(). Here, .ndim returns 1 indicating it's 1-dimensional, and .shape returns (2), meaning the vector has 2 elements.

* Matrix (Rank 2 Tensor): A matrix is a 2-dimensional array of numbers. The example creates a 2x2 matrix with torch.tensor([[7, 8], [9, 10]]). .ndim shows it's 2-dimensional, and .shape returns (2, 2), indicating 2 rows and 2 columns.

* Higher-Dimensional Tensor (Rank 3+ Tensor): Tensors can have three or more dimensions. The provided code creates a tensor with dimensions (1, 3, 3), meaning it contains a 3x3 matrix in a 3-dimensional space. .ndim confirms it's 3-dimensional. The shape is described as having 1 matrix that contains 3 rows and 3 columns each.

This code is a basic introduction to the concept of tensors in PyTorch, demonstrating how to create them and inspect their properties like dimensionality and shape. Understanding these properties is essential for working with data in machine learning and deep learning applications.

---

**Naming Conventions**
* Scalar (dimension = 0) - lower-case $a$
* Vector (dimension = 1) - lower-case $y$
* Matrix (dimension = 2) - upper-case $Q$
* Tensor (dimension ≥ 3) - upper-case $X$

In [3]:
# Scalar (tensor rank 0)
scalar = torch.tensor(7) # A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor

print(scalar)
print(scalar.ndim) # checks how many dimensions does scalar have
print(scalar.shape)
print(scalar.item()) # Get tensor back as Python int


tensor(7)
0
torch.Size([])
7


> The .item() method is specific to tensors that have a single element. Its purpose is to extract the value of that single element as a standard Python number (int or float). It's particularly useful when you're working with tensors that result from some computations, and you want to convert the result into a Python scalar.

> Attempting to use .item() on a tensor with more than one element will result in an error because it's not clear which element should be converted to a Python scalar. The method is designed to ensure that it's only used when there's exactly one element in the tensor, thereby avoiding ambiguous situations.

In [4]:
# Vector (tensor rank 1)
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim) # checks how many dimension does vector have
print(vector.shape) # outputs the shape of the vector, eg 2 by 1.

tensor([7, 7])
1
torch.Size([2])


In [5]:
# Matrix (tensor rank 2)
MATRIX = torch.tensor([[7, 8], [9, 10]])
print(MATRIX)
print(MATRIX.ndim) # checks how many dimension does MATRIX have
print(MATRIX.shape) # outputs the shape of the matrix

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [6]:
# Tensor (tensor rank 3+)
TENSOR = torch.tensor([[[1, 2, 3],   #[ <-- dim=0[ <-- dim=1 [ <-- dim=2 ]]]
                        [4, 5, 6],
                        [6, 7, 8]]])
print(TENSOR)
print(TENSOR.ndim) # checks how many dimension does TENSOR have

print(TENSOR.shape) # outputs the shape of the tensor
                    # torch.Size([1, 3, 3]) means that you have 1x 3 by 3 matrix in this tensor.
                    # torch.Size([dim=0, dim=1, dim=2])
                    # alternatively, dim=0 contains 1 value (matrix), dim=1 contains 3 values (vector), dim=2 contains 3 scalars each.


tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])
3
torch.Size([1, 3, 3])


### Random Tensors



**Why random tensors?**

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Workflow:

> `Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

PyTorch Docs (torch.rand()) url - https://pytorch.org/docs/stable/generated/torch.rand.html


In [7]:
# Create a random tensor of size (4, 3, 4)
random_tensor = torch.rand(4, 3, 4) # can write "touch.rand(size=(4, 3, 4))" // both are acceptable
print(random_tensor)

tensor([[[3.1819e-01, 6.4301e-01, 3.7265e-01, 8.3622e-01],
         [4.6241e-01, 1.2688e-01, 1.1209e-01, 7.0268e-01],
         [1.1939e-01, 6.4807e-01, 8.0514e-01, 3.4811e-01]],

        [[2.2211e-01, 9.2608e-01, 6.2135e-01, 9.7105e-01],
         [3.1338e-01, 9.5852e-01, 8.3803e-01, 6.9827e-02],
         [1.1109e-01, 8.6737e-01, 8.6464e-01, 2.2208e-01]],

        [[4.3882e-01, 7.0608e-03, 2.1993e-01, 3.3212e-04],
         [3.3231e-01, 2.2853e-01, 8.7166e-01, 3.1274e-01],
         [7.4625e-01, 7.5750e-01, 6.0879e-01, 1.6560e-01]],

        [[4.6921e-01, 6.4979e-01, 7.2260e-01, 5.1278e-01],
         [4.5194e-01, 4.7757e-02, 7.1894e-01, 2.0497e-01],
         [1.6052e-01, 4.9845e-01, 2.7172e-01, 5.3574e-01]]])


In [8]:
print(random_tensor.ndim) # checks how many dimension does random_tensor have
print(random_tensor.shape) # outputs the shape of the random_tensor

3
torch.Size([4, 3, 4])


In [9]:
# Create a random tensor with simillar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # alternative is colour channel coming first, eg. size=(3, 224, 224) // both image dimension of 224x224
print(random_image_size_tensor.ndim) # checks dimension of random_image_size_tensor
print(random_image_size_tensor.shape) # outputs shape of random_image_size_tensor

# random tensors are so valuable because neural network starts with random data -> look at data -> update the random numbers -> look at data .....

3
torch.Size([224, 224, 3])


### Zeros and Ones

In [10]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros * random_tensor) # multiply zero tensor with random tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [11]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones)
print(ones * random_tensor) # multiply zero tensor with random tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[[3.1819e-01, 6.4301e-01, 3.7265e-01, 8.3622e-01],
         [4.6241e-01, 1.2688e-01, 1.1209e-01, 7.0268e-01],
         [1.1939e-01, 6.4807e-01, 8.0514e-01, 3.4811e-01]],

        [[2.2211e-01, 9.2608e-01, 6.2135e-01, 9.7105e-01],
         [3.1338e-01, 9.5852e-01, 8.3803e-01, 6.9827e-02],
         [1.1109e-01, 8.6737e-01, 8.6464e-01, 2.2208e-01]],

        [[4.3882e-01, 7.0608e-03, 2.1993e-01, 3.3212e-04],
         [3.3231e-01, 2.2853e-01, 8.7166e-01, 3.1274e-01],
         [7.4625e-01, 7.5750e-01, 6.0879e-01, 1.6560e-01]],

        [[4.6921e-01, 6.4979e-01, 7.2260e-01, 5.1278e-01],
         [4.5194e-01, 4.7757e-02, 7.1894e-01, 2.0497e-01],
         [1.6052e-01, 4.9845e-01, 2.7172e-01, 5.3574e-01]]])


In [12]:
# datatype
print(zeros.dtype)
print(ones.dtype)
print(random_tensor.dtype)

torch.float32
torch.float32
torch.float32


### Creating a Range of Tensors and Tensors-like



PyTorch docs for "torch.arange()" - https://pytorch.org/docs/stable/generated/torch.arange.html

In [13]:
#torch.range(0, 10) # depracated method, use "torch.arange()" instead
one_to_ten = torch.arange(0, 10) # tensor.arange() starts at start_int, ends at end_int - 1.
print(one_to_ten)
one_to_k = torch.arange(start=0, end=1000, step=77)
print(one_to_k)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])


In [14]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten) # this will get you a tensor full of zeros, which is the same shape as the tensor input, ie "one_to_ten"
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Datatypes



**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype (eg. happens when inconsistent dtype substitution between tensors)
2. Tensors not right shape (eg. happens in matrix multiplication)
3. Tensors not on the right device (eg. device="cpu" vs device="cuda", and device agnostic code)

In [15]:
# Float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], # even if dtype=None, PyTorch will then revert to default datatype
                               dtype=None, # what datatype is the tensor (e.g float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor's operation
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([1., 2., 3.])
torch.float32


In [16]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16) # convert float_32_tensor to float_16_tensor // alternatively, torch.half would also work
print(float_16_tensor)
print(float_16_tensor.dtype) # float_16_tensor is now float 16

tensor([1., 2., 3.], dtype=torch.float16)
torch.float16


In [17]:
# suprisingly no error raised even though discrepancy in dtype; normal behavious, but can be an issue with large neural network,
# but preferably don't use different' dtype
print(float_16_tensor * float_32_tensor) # works even if multipled by torch.long or torch.int32, etc

tensor([1., 4., 9.])


### Getting Information from Tensors (Tensor Attributes)



1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get a shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [18]:
# Create a test tensor
some_tensor = torch.rand(2, 3, 4)
print(some_tensor)

tensor([[[0.4220, 0.1777, 0.6274, 0.5070],
         [0.2611, 0.7993, 0.5080, 0.4965],
         [0.5495, 0.5899, 0.1230, 0.3934]],

        [[0.0251, 0.0667, 0.3379, 0.8956],
         [0.4043, 0.7929, 0.4926, 0.7320],
         [0.7707, 0.9150, 0.4982, 0.8741]]])


In [19]:
# Find out details about some_tensor
print(f"Datatype of tensor : {some_tensor.dtype }")
print(f"Shape of tensor    : {some_tensor.shape }")  # "some_tensor.shape" and "some_tensor.size()" does the same thing (shape is attribute, .size() is founction)
print(f"Device of tensor   : {some_tensor.device}")

Datatype of tensor : torch.float32
Shape of tensor    : torch.Size([2, 3, 4])
Device of tensor   : cpu


### Manipulating Tensors (Tensor Operations)



Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [20]:
# Create a Tensor
tensor = torch.tensor([1, 2, 3]) # initialised from Python list or array
print(tensor)
print(tensor + 10) # addition
print(tensor - 10) # subtraction
print(tensor * 10) # multiplication
print(tensor / 10) # division

tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [21]:
# Try out PyTorch built-in functions
print(torch.add(tensor, 10)) # addition
print(torch.sub(tensor, 10)) # subtraction
print(torch.mul(tensor, 10)) # multiplication
print(torch.div(tensor, 10)) # division

print(torch.abs(tensor)) # absolute value
print(torch.sqrt(tensor)) # square root
print(torch.exp(tensor)) # exponential

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
tensor([1, 2, 3])
tensor([1.0000, 1.4142, 1.7321])
tensor([ 2.7183,  7.3891, 20.0855])


### Matrix Multiplication




Two main ways of performing multiplication in neural networks and deep learning are:
1. Element-wise multiplication
2. Matrix multiplication (dot product) [dot product and matrix multiplication is used interchangeably]

URL: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Random Note: To multiply a matrix by another matrix, we need to do the "dot product" of rows and columns... (rewatch 3Blue1Brown if recap needed on linear algebra)

---

Regarding anatomy of Matrix, below as an example is a **4x2 matrix**, pay attention that the int*int order of matrix is classified by `_rows_x_columns_`. Use `tensor.shape`, to find the dimensions of the matrix:

`[`

>  `[1, 2],`

>  `[3, 4],`

>  `[5, 6],`

>  `[7, 8]`

`]`

There are 2 main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:

* `(3x2) @ (3x2)` <-- this won't work
* `(2x3) @ (3x2)` <-- this will work
* `(3x2) @ (2x2)` <-- this will work

2. The resulting matrix has the shape of the **outer dimension**:

* `(4x3) @ (3x6) = (4x6)` <-- 4x6 matrix outputted
* `(3x1) @ (1x7) = (3x7)` <-- 3x7 matrix outputted


> Note: regarding matrix multiplication syntax, `tensor @ tensor`, is the same as `torch.matmul(tensor, tensor)`, same performance wise etc, the '@' operator is an overload of the \__matmul__ magic method in the PyTorch's tensor class.

In [22]:
# Element-wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

print(torch.rand(4, 2).shape) # outputs the shape of a 4x2 matrix
print((torch.rand(4, 3) @ torch.rand(3, 6)).shape) # 4x3 @ 3x6 -> 4x6
print((torch.rand(3, 1) @ torch.rand(1, 7)).shape) # 3x1 @ 1x7 -> 3x7

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
torch.Size([4, 2])
torch.Size([4, 6])
torch.Size([3, 7])


In [23]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [24]:
%%time
value=0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.56 ms, sys: 1.11 ms, total: 3.67 ms
Wall time: 6.73 ms


In [25]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.28 ms, sys: 55 µs, total: 1.34 ms
Wall time: 1.36 ms


tensor(14)

### One of the Most Common Errors in Deep Learning: Shape Errors



In [26]:
# Shapes for Matrix Multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10, 1],
                         [8, 11, 2]])

#torch.mm(tensor_A, tensor_B)  # torch.mm() is the same as torch.matmul() // It's an Alias.
torch.matmul(tensor_A, tensor_B) # As see, need to be 3x2 @ 2x3, which is multipliable. Which this outputs 3x3

tensor([[ 23,  32,   5],
        [ 53,  74,  11],
        [ 83, 116,  17]])

A way to fix our tensor shape issues, is that we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [27]:
print("Original Shape:", tensor_A.shape)
print("Transposed Shape:", tensor_A.T.shape)

Original Shape: torch.Size([3, 2])
Transposed Shape: torch.Size([2, 3])


### Finding the min, max, mean, sum, etc. (Tensor Aggregation)



Definition of "Aggregation": The formation of a number of things into a cluster.


In [28]:
# Create a Tensor

x = torch.arange(0, 100, 10)
print(x)

print(torch.min(x), x.min()) # Find the Min
print(torch.max(x), x.max()) # Find the Max
print(torch.mean(x.float()), x.type(torch.float32).mean()) # Find the Mean // When calculating mean, needs to be in float or complex dtype. Long doesn't work. Refer to MISC.
print(torch.sum(x), x.sum()) # Find the Sum


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) tensor(0)
tensor(90) tensor(90)
tensor(45.) tensor(45.)
tensor(450) tensor(450)


### Finding the Positional min and max

In [29]:
print(x) # outputs "tensor.arange(0, 100, 10)"

# Find the position in tensor that has the minimum value with "argmin()" -> returns index position of target tensor where the minimum value occurs
print(x.argmin(), x[x.argmin()])

# Find the position in tensor that has the maximum value with "argmax()" -> returns index position of target tensor where the maximum value occurs
print(x.argmax(), x[x.argmax()])

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) tensor(0)
tensor(9) tensor(90)


### Reshaping, Stacking, Squeezing and Unsqueezing Tensors



* Reshaping - Reshapes an input tensor to a defined shape, eg 1x12 matrix to a 2x6 matrix of a 4x3 matrix
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [36]:
x = torch.arange(0., 12.)
print(x, x.shape, '\n')

# Add an Extra Dimension -- tensor.reshape()
x_reshaped = x.reshape(2, 6)  # reshapes input 1x12 matrix to 2x6 matrix
print("Reshapes 1x12 matrix to 2x6 matrix")
print(x_reshaped, x_reshaped.shape, '\n')

x_reshaped = x.reshape(4, 3)  # reshapes input 1x12 matrix to 4x3 matrix
print("Reshapes 1x12 matrix to 4x3 matrix")
print(x_reshaped, x_reshaped.shape, '\n')

# Quick note regarding tensor.shape
#   For Scalar, it will results in "torch.Size([])"                    <-- indicating 0th dimension
#   For Vector, it will results in "torch.Size([int])"                 <-- indicating 1st dimension
#   For Matrix, it will results in "torch.Size([int, int])"            <-- indicating 2nd dimension
#   For Tensor, it will results in "torch.Size([int, int, int, ...])"  <-- indicating 3+  dimension

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]) torch.Size([12]) 

Reshapes 1x12 matrix to 2x6 matrix
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]) torch.Size([2, 6]) 

Reshapes 1x12 matrix to 4x3 matrix
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]]) torch.Size([4, 3]) 



In [31]:
newTensor = torch.arange(0., 12.)

# Change the View -- tensor.view()
tempView = newTensor.view(2, 6)
print(tempView, tempView.shape)

#Changing "tempView" tensor variable, changes "x" tensor variable (because a view of a tensor shares the same memory as the original input)
tempView[:, 3] = 100  # refer to MISC regarding slicing
print("\n", tempView)
print(newTensor)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]) torch.Size([2, 6])

 tensor([[  0.,   1.,   2., 100.,   4.,   5.],
        [  6.,   7.,   8., 100.,  10.,  11.]])
tensor([  0.,   1.,   2., 100.,   4.,   5.,   6.,   7.,   8., 100.,  10.,  11.])


In [44]:
# Stack tensors on top of each other
x_stacked = torch.stack((x, x, x, x), dim=0)
print(x_stacked, x_stacked.shape)
x_stacked = torch.stack((x, x, x, x), dim=1)
print(x_stacked, x_stacked.shape)

x_stacked = torch.stack((x, x, x, x), dim=-1) # dim=-1 refers to last dimension of tensor
print(x_stacked, x_stacked.shape)
x_stacked = torch.stack((x, x, x, x), dim=-2) # dim=-2 refers to second to last dimension of tensor
print(x_stacked, x_stacked.shape)

# NOTE: Refer to MISC on Stack in PyTorch

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]) torch.Size([4, 12])
tensor([[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.]]) torch.Size([12, 4])
tensor([[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10.,

In [60]:
print(x_reshaped)
print(x_reshaped.shape, '\n')

# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
x_unsqueezed = x_reshaped.unsqueeze(dim=0).unsqueeze(dim=2) # turns torch.Size([4, 3]) to torch.Size([1, 4, 1, 3])    // adding 2 dimensions in this case

print(x_unsqueezed)
print(x_unsqueezed.shape, '\n')

# torch.squeeze() - removes all single dimensions from a target tensor
x_squeezed = x_reshaped.squeeze() # turns torch.Size([1, 4, 1, 3]) to torch.Size([4, 3]) // All single-dimensions removed

print(x_squeezed)
print(x_squeezed.shape, '\n')

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3]) 

tensor([[[[ 0.,  1.,  2.]],

         [[ 3.,  4.,  5.]],

         [[ 6.,  7.,  8.]],

         [[ 9., 10., 11.]]]])
torch.Size([1, 4, 1, 3]) 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3]) 



In [71]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
colour = torch.rand(size=(4, 6, 3))
print(colour)                         # [height, width, colour_channels]
print(colour.shape, '\n')

# Permute the original colour tensor to rearrange the axis (or dim) order
colour_permuted = colour.permute(2, 0, 1) # turns torch.Size([4, 3]) to torch.Size([3, 4])

print(colour_permuted)
print(colour_permuted.shape, '\n')    # [colour_channels, height, width]

# Indexing -- Original + Permuted
print(colour[1, 5, 2], colour_permuted[2, 1, 5]) # both this line and below accesses the same value, notice how their ith index is changed based on .permute() ordering
print(colour[2, 1, 2], colour_permuted[2, 2, 1])

tensor([[[0.8987, 0.1504, 0.7831],
         [0.1949, 0.7430, 0.1381],
         [0.4506, 0.0641, 0.9216],
         [0.6601, 0.7801, 0.0390],
         [0.9887, 0.2105, 0.5448],
         [0.1835, 0.6150, 0.4326]],

        [[0.2583, 0.8937, 0.6003],
         [0.4536, 0.0735, 0.6484],
         [0.6436, 0.9835, 0.2535],
         [0.5457, 0.1390, 0.8481],
         [0.7183, 0.9208, 0.3214],
         [0.1480, 0.8678, 0.7758]],

        [[0.2079, 0.0541, 0.8964],
         [0.5032, 0.0816, 0.6990],
         [0.4493, 0.0773, 0.3050],
         [0.3787, 0.2513, 0.6509],
         [0.2784, 0.4532, 0.0607],
         [0.8046, 0.1965, 0.7660]],

        [[0.9633, 0.6317, 0.0680],
         [0.1485, 0.8863, 0.6642],
         [0.5199, 0.1377, 0.6971],
         [0.9700, 0.9300, 0.3529],
         [0.7233, 0.5011, 0.0073],
         [0.2435, 0.9157, 0.4473]]])
torch.Size([4, 6, 3]) 

tensor([[[0.8987, 0.1949, 0.4506, 0.6601, 0.9887, 0.1835],
         [0.2583, 0.4536, 0.6436, 0.5457, 0.7183, 0.1480],
         [

# Miscellaneous


###Miscellaneous Notes - Image Tensor

**GPT Prompt:** In tensor-speak (the language used to describe tensors), the tensor would have three dimensions, one for colour_channels, height and width.

<br>

**GPT Answer:**

The quote you've provided talks about how to describe the structure of a tensor, particularly in the context of image data, using the specific terminology or "language" associated with tensors.

In the realm of machine learning and computer vision, images are commonly represented as tensors. A tensor, in this context, is essentially a multi-dimensional array. For an image, these dimensions correspond to different aspects of the data it contains:

Color Channels: The number of channels in an image represents the depth of color information. For instance, a standard RGB (Red, Green, Blue) image has three color channels. Each channel stores intensity values for its respective color across the image. There are also grayscale images, which have just one channel, and other formats that may have more channels (like RGBA, where the A stands for Alpha or transparency).

Height: This dimension represents the vertical size of the image in pixels.

Width: This dimension represents the horizontal size of the image in pixels.

So, when the quote mentions a tensor having "three dimensions, one for color_channels, height, and width," it's describing how an image is structured in a way that's understood by tensor operations. For a color image in the RGB format, you could conceptualize it as a 3D tensor:

The first dimension corresponds to the color channels (3 for RGB).
The second dimension corresponds to the height of the image in pixels.
The third dimension corresponds to the width of the image in pixels.
Thus, if you have a 1080x1920 pixel RGB image, in tensor-speak, you would describe it as having dimensions of 3x1080x1920, where 3 represents the RGB channels, 1080 represents the height, and 1920 represents the width.

Understanding this terminology is crucial for working with image data in machine learning frameworks like TensorFlow or PyTorch, as it affects how you process, manipulate, and train models with image data.

<br>
---
<br>

Here's an example of what a tensor array for a 10x10 image with RGBA channels might look like. Each entry in this array is a randomly generated integer between 0 and 255, representing the intensity of the Red, Green, Blue, and Alpha (transparency) channels at each pixel:

---
```
Array shape: (4, 10, 10)

array([[[203, 178,  63, 203,  19,  80,  77,  99, 226, 227], #red
        [148,  31, 141, 150, 187, 184, 214,  10,  40,  95],
        [ 96,  76, 213, 117,  79, 224, 174,  44,   7, 236],
        [182,  25, 242, 120, 207, 194,  52,  38,  42, 222],
        [105, 193, 169, 146, 221,  76, 179,  84, 109, 222],
        [  4, 105,  73,  54, 242, 172, 238,  23,  89, 192],
        [ 79,  26,  75, 133,  92,  10, 115, 114,  87, 227],
        [124, 183,  36, 176, 115, 246, 151, 227,  54,   1],
        [  8, 255, 102, 242, 116,  93,  10, 184, 184,   1],
        [161, 118,  98, 150,  89, 208,  76,  77,  58, 136]],

       [[171, 231, 224, 128, 149, 101,  72, 167,  57, 178], #green
        [170,   3, 175, 194, 243,  77, 188,  97, 197, 206],
        [250, 197,  22, 191, 215, 156,  73,  38, 196,  34],
        [255, 164, 187,  28, 114, 140,  65, 162,  74, 168],
        [212, 127, 120, 162,  86,  22, 141, 126,  81, 167],
        [168, 201,  21, 219, 148,  70, 102, 206, 111, 214],
        [ 23, 204, 152,  56, 164, 110, 197, 213,  28, 206],
        [162, 149, 100, 206,  25,  88, 161,  83, 173, 177],
        [218,  38,  76, 220,  37,  36,  11, 228,   0, 107],
        [ 29,  94, 173, 170,  31, 207, 251,  65, 205,  95]],

       [[ 17, 117, 145,  64, 124,  20, 242, 202, 159,  72], #blue
        [214, 102, 124, 170, 191,  93,  23, 251, 249,  62],
        [ 25, 245, 169, 116, 131,  39,  68, 147,  79,  90],
        [111,  33,  35, 196, 197, 170,  51, 197,  62,  70],
        [ 47,  41, 113, 166, 202,  24, 242, 246,  68, 245],
        [174,   4,  77,  83,  42,  65, 183,  58, 113,  44],
        [221, 117, 252, 153, 119,  45, 137, 104,  58,  57],
        [168, 231, 210, 239,  32,  30,   9, 150,  95, 214],
        [127, 240,  56, 200, 161, 137, 197,   6, 231,  72],
        [  4, 109,  53,  11, 197, 217,  88,   1, 249, 254]],

       [[ 23, 252, 127,   8,  58, 222, 123,   6,  14, 108], #alpha
        [  4, 195,  26, 177,  59, 145, 199, 167, 181,  93],
        [  4, 119, 204, 182, 108,  53, 175, 159,  83,  50],
        [ 47, 233, 103, 198,  84, 134,  42, 145,  93, 235],
        [ 35, 165, 152,  77, 101, 153, 242, 206, 109,   9],
        [ 78, 210, 182, 151,  48, 209, 199,  33, 138,  95],
        [226, 206, 106,  47,  54,  49, 178, 107, 112, 105],
        [195,  17,  24, 144,  91,  14, 102, 123, 246, 231],
        [253, 137,  22, 133,  19, 192, 166,  24, 145,  78],
        [ 69, 165, 135, 255, 122, 125, 135, 160, 174,  54]]], dtype=uint8)
```
---

This representation shows a 4-dimensional tensor where:

* The first dimension corresponds to the color channels (RGBA), so there are 4 layers or slices.
* The second and third dimensions correspond to the height and width of the image, respectively, both set to 10 pixels in this example.

Each "layer" or slice of the tensor represents one of the RGBA channels across the entire image. The values within each layer represent the intensity of that channel for each pixel, with 0 being no intensity (or completely transparent for the alpha channel) and 255 being the maximum intensity. ​​






In Jupyter notebooks, which include Google Colab notebooks, you do not always need to use the print() function to display output. This environment is designed for interactive computing, and it has a feature that automatically displays the result of the last operation in each cell.

When you run a cell in a Jupyter notebook (or Google Colab, which is based on Jupyter), the following rules apply:

The last line of code in a cell, when executed, will have its result displayed below the cell, even if it is not printed with the print() function. This is known as the cell's output.
If the last line of code does not produce any output, nothing is displayed.
If you have other lines of code in the cell whose output you wish to display, you need to explicitly use print() or another display function for those lines.
This feature is especially useful for quick data exploration and analysis, as it allows you to see the results immediately without needing to use print() every time. However, if you want to format the output or display multiple outputs within a cell, you'll need to use print() or another suitable display function.

**Notes Regarding Why you don't need to declare print() to output value in Google Colab**

<br>

In Jupyter notebooks, which include Google Colab notebooks, you do not always need to use the $print()$ function to display output. This environment is designed for interactive computing, and it has a feature that automatically displays the result of the last operation in each cell.

When you run a cell in a Jupyter notebook (or Google Colab, which is based on Jupyter), the following rules apply:

1. The last line of code in a cell, when executed, will have its result displayed below the cell, even if it is not printed with the $print()$ function. This is known as the cell's output.
2. If the last line of code does not produce any output, nothing is displayed.
3. If you have other lines of code in the cell whose output you wish to display, you need to explicitly use $print()$ or another display function for those lines.


This feature is especially useful for quick data exploration and analysis, as it allows you to see the results immediately without needing to use $print()$ every time. However, if you want to format the output or display multiple outputs within a cell, you'll need to use $print()$ or another suitable display function.

### Miscellaneous Notes - Dimensions

**GPT Prompt**: what even is ndim in torch, as in, what is dimension of tensors even. as scalars are normally assosciated with the number line 1st dimension, however here it is assosicated with the 0th dimension. can i know why does tensorflow consider scalar as 0th, vector as 1st, matrix 2nd etc

<br>

**GPT Answer**:

The concept of dimensionality in tensors (as used in libraries like PyTorch and TensorFlow) is rooted in the mathematical definition of dimensions in linear algebra, but it's also slightly adapted to fit programming and data structure paradigms.

**Understanding Dimensions**

* Dimensionality: In the context of tensors, the dimensionality (or rank) refers to the number of indices required to uniquely select each element of the tensor. This concept is directly tied to how data can be organized and represented in structured forms:
> * A scalar can be thought of as a single number. It doesn't contain any axes (or directions), so it's considered 0-dimensional. You don't need any index to access it because it's just a single value.
> * A vector is a 1-dimensional array. You need one index to access each element. Think of it as a line where each element can be located at a certain position along that line.
> * A matrix is a 2-dimensional array. You need two indices to access each element (one for the row and one for the column). It can be visualized as a plane or grid where positions are defined by two coordinates.
> * Higher-dimensional tensors (3D, 4D, etc.) require more indices to access each element and represent more complex structures (like a cube for a 3D tensor).

**Why Scalars are Considered 0-Dimensional**

The designation of scalars as 0-dimensional in libraries like TensorFlow and PyTorch is consistent with how dimensions are mathematically defined. Since a scalar does not require any indices to access (it's just a single value), it is considered 0-dimensional. This definition helps maintain consistency across mathematical theory and its implementation in programming:

* It aligns with the mathematical concept of a dimension as the number of coordinates needed to specify a point within it.
* It provides a basis for defining operations and transformations on tensors in a way that is consistent regardless of their rank.

**Practical Implications**

This conceptual framework has practical implications in programming and data processing:

* Generalization: By defining a scalar as a 0-dimensional tensor, vectors as 1-dimensional, matrices as 2-dimensional, and so on, libraries can offer a unified and consistent API for tensor operations that works across tensors of any dimensionality.
* Broadcasting and Shape Manipulation: Understanding dimensionality is crucial for operations that involve multiple tensors, especially when their shapes differ. It allows for the implementation of broadcasting rules, where tensors of different shapes are used together in operations.
* Data Representation: This hierarchical structure (scalar < vector < matrix < tensor) provides an intuitive way to represent increasingly complex data. For instance, a 3D tensor could represent a sequence of images (2D tensors), where each image is a matrix of pixel values.

In summary, the classification of scalars as 0-dimensional and so on up the hierarchy to higher-dimensional tensors is a logical extension of mathematical principles into programming constructs, allowing for more versatile and powerful data manipulation capabilities in libraries like PyTorch and TensorFlow.

### Miscellaneous Notes - tensor.mean() Dtype 'Long' issue

**GPT Prompt:** Why does long not work with .mean() in PyTorch

**GPT Answer:** In PyTorch, the .mean() operation computes the arithmetic mean of all the elements in the tensor. For the mean to be meaningful, especially in the context of floating-point arithmetic, the operation is defined only for tensors with floating point or complex numbers. This is because the mean is not always an integer value, and rounding to an integer could lead to loss of precision and incorrect calculations in subsequent operations.

The tensor you are working with has been created with the default integer type (torch.int64 or Long type in PyTorch), as inferred from the torch.arange function. To calculate the mean, you need to first convert it to a floating-point type. You can do this by using the .float() or .to() methods on the tensor.

Here's how you can modify your tensor to compute the mean:

```
x_float = x.float()  # Convert x to a float tensor
print(torch.mean(x_float), x_float.mean())  # Now you can compute the mean
```

This converts the tensor x to a floating point tensor (torch.float32), which allows the .mean() method to work correctly.

### Miscellaneous Notes - Regarding Slicing [:] in Python

**GPT Answer Regarding Slicing[:] in Python**
In Python, slicing is a feature that allows you to access a portion of a sequence type (like lists, strings, tuples) or array-like objects (like NumPy arrays and PyTorch tensors). The slicing operator [:] is used to access elements of an iterable based on their indices. Here are some examples of how slicing works:

---

**Lists**

* Let's start with a simple list:
> `my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`
* Accessing all elements:
> `all_elements = my_list[:]  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`
* Accessing the first 5 elements:
> `first_five = my_list[:5]  # [0, 1, 2, 3, 4]`
* Accessing elements from index 5 to the end:
> `from_five_onwards = my_list[5:]  # [5, 6, 7, 8, 9]`
* Accessing elements from index 3 to 7 (not including 7):
> `subset = my_list[3:7]  # [3, 4, 5, 6]`
* Accessing elements with a step (every second element):
> `every_second = my_list[::2]  # [0, 2, 4, 6, 8]`
* Accessing elements in reverse:
> `reversed_list = my_list[::-1]  # [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]`

---

**Strings**

* Slicing works similarly with strings:
> `my_string = "Hello, World!"`

* Accessing all characters:
> `all_chars = my_string[:]  # "Hello, World!"`

* Accessing the first 5 characters:
> `first_five = my_string[:5]  # "Hello"`

* Accessing characters from index 7 to the end:
> `from_seven_onwards = my_string[7:]  # "World!"`

---

**NumPy Arrays**

* For NumPy arrays (and similarly for PyTorch tensors), slicing can be multidimensional:

> ```
import numpy as np
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
> ```

* Accessing the entire array:
> `all_elements = my_array[:]  # array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`

* Accessing the first two rows:
> `first_two_rows = my_array[:2]  # array([[1, 2, 3], [4, 5, 6]])`

* Accessing the second column:
> `second_column = my_array[:, 1]  # array([2, 5, 8])`

Accessing a submatrix (first two rows, last two columns):
> `submatrix = my_array[:2, 1:]  # array([[2, 3], [5, 6]])`

---

Slicing is a powerful tool in Python that lets you retrieve elements efficiently from sequences and array-like objects without the need for explicit loops.

### Miscellaneous Notes - torch.stack() + torch.squeeze()



#### torch.stack(), torch.vstack(), torch.hstack()

GPT Prompt: Explain to me what does `torch.stack()` do?

GPT Answer:

`torch.stack()` is a function in PyTorch, a popular open-source machine learning library, that is used to concatenate a sequence of tensors along a new dimension. All tensors in the sequence **must have the same shape**. The function is particularly useful when you want to combine tensors in a way that creates an additional dimension, rather than simply joining them end-to-end as in concatenation.

Here's a more detailed breakdown of its functionality:

* Parameters: The `torch.stack(tensors, dim=0, *, out=None) -> Tensor` function takes several parameters, the most important of which are:

  * tensors: a sequence of tensors to concatenate. These tensors must all have the same shape.
  * dim: the dimension along which to concatenate the tensors. This is a new dimension that the tensors will be stacked along.
  * out (Tensor, optional) – the output tensor.

* Behavior: `torch.stack()` joins a sequence of tensors along a new dimension. All tensors in the sequence are expanded to have one additional dimension, and then they are joined along this new dimension. The position of this new dimension in the resultant tensor is specified by the dim parameter.

* Result: The result of `torch.stack()` is a new tensor with one more dimension than the original tensors. For example, if you stack three 2D tensors (each of shape [2, 3]) along a new first dimension (`dim=0`), the resulting tensor will have the shape [3, 2, 3].

Here's an example to illustrate its use:

 ```
import torch

# Creating two 2D tensors of shape [2, 3]
tensor1 = torch.randn(2, 3)
tensor2 = torch.randn(2, 3)

# Stacking the two tensors along a new dimension (creates a new dimension at position 0)
result = torch.stack((tensor1, tensor2), dim=0)

print(result.shape)  # Output will be: torch.Size([2, 2, 3])
```

In this example, tensor1 and tensor2 are stacked along a new first dimension (dim=0), resulting in a tensor of shape [2, 2, 3], indicating that there are 2 tensors, each of shape [2, 3], stacked together.

---
GPT Prompt: Then what does param dim=-1 and dim=-2 do?

GPT Answer:

In PyTorch, `torch.stack()` is a function used to concatenate a sequence of tensors along a new dimension. All tensors in the sequence must have the same shape. The function creates a new tensor by stacking the input tensors, effectively adding one additional dimension to the resultant tensor, where each input tensor becomes a slice along the newly created dimension.

The `dim` parameter in `torch.stack()` specifies the dimension along which the tensors are stacked. The dimensions are zero-indexed, meaning dim=0 would stack the tensors along a new first dimension, and the original dimensions of the tensors would follow after this new dimension.

Regarding `dim=-1` and `dim=-2`:

* `dim=-1` refers to the last dimension of the tensor. When you use dim=-1 in torch.stack(), it means you're stacking the tensors along the last dimension. After stacking, this newly created dimension becomes the new last dimension of the resultant tensor.

* `dim=-2` refers to the second-to-last dimension of the tensor. Using dim=-2 in torch.stack() means the tensors are stacked along the second-to-last dimension, making the newly created dimension the new second-to-last dimension of the resultant tensor.

These negative indices are useful for specifying dimensions relative to the end of the tensor, which can be especially handy when you're dealing with tensors of varying dimensions and you want to stack them along one of the last few dimensions without explicitly calculating or hard-coding the dimension index.

---

GPT Prompt: Then what is torch.vstack() and torch.hstack()

GPT Answer:

In PyTorch, torch.vstack() and torch.hstack() are functions used to concatenate tensors vertically and horizontally, respectively. These functions provide a convenient way to stack tensors along specific axes and are particularly useful when working with 2D tensors (matrices) but can also be applied to tensors with more dimensions. Here's a brief overview of each:

`torch.vstack()`

* **Vertical stacking (vstack):** This function stacks tensors vertically, which is equivalent to concatenating tensors along the first dimension (rows) for 2D tensors, or more generally, along a new first dimension for tensors of any shape. It's akin to stacking matrices on top of each other or appending rows to a matrix.
* **Usage:** It's commonly used when you have tensors of the same width (i.e., the same size in all dimensions except for the first) and you want to combine them into a single tensor with greater height (more rows).

`torch.hstack()`

* **Horizontal stacking (hstack):** This function stacks tensors horizontally, equivalent to concatenating tensors along the second dimension (columns) for 2D tensors, or more generally, along the last dimension for 1D tensors. For tensors with more than two dimensions, it concatenates along the last dimension, which increases the size of that dimension.
* **Usage:** It's used when you have tensors of the same height (i.e., the same size in all dimensions except for the second in the case of 2D tensors) and you want to combine them into a single tensor with greater width (more columns).

These functions are particularly helpful in data manipulation and preprocessing tasks, such as combining data from different sources into a single dataset or reshaping data to fit the input requirements of a model.

**GPT Prompt:** Explain to me regarding torch.squeeze() and torch.unsqueeze()

**GPT Answer:**

In PyTorch, `torch.squeeze()` and `torch.unsqueeze()` are two functions used for modifying the dimensions of tensors, specifically for removing and adding dimensions of size 1, respectively. These functions are very useful for tensor shape manipulation, allowing for more flexible operations and easier integration with APIs expecting certain tensor shapes.

<br>

`torch.squeeze()`

* Purpose: Removes all dimensions of size 1 from the tensor. If a specific dimension is given as an argument, torch.squeeze() removes the given dimension only if it is of size 1; otherwise, the tensor is returned unchanged.
* Usage: This is useful when you want to eliminate redundant dimensions from your tensor, making your data more compact or ensuring it fits certain APIs that do not accept tensors with singleton dimensions. For example, if you have a tensor of shape (1, 3, 1, 5), applying squeeze() would reduce its shape to (3, 5).
* Parameter:
  * input (Tensor) – the input tensor.
  * dim (int or tuple of ints, optional) – if given, the input will be squeezed only in the specified dimensions.
* Syntax Example:
> `squeezed_tensor = torch.squeeze(input_tensor, dim=None)`

  Here, input_tensor is the tensor you want to squeeze, and dim is an optional argument specifying the dimension to squeeze. If dim is not provided, all dimensions of size 1 are removed.

`torch.unsqueeze()`

* Purpose: Adds a dimension of size 1 to the tensor at the specified dimension. This is the inverse operation of squeeze(), allowing you to expand the dimensions of your tensor.
* Usage: This is particularly useful when you need to increase the dimensionality of a tensor for it to be compatible with certain operations that expect tensors of a certain shape. For instance, if you have a tensor of shape (3, 5) and you want to add a singleton dimension as the first dimension, you would end up with a shape of (1, 3, 5).
* Syntax Example:
> `unsqueezed_tensor = torch.unsqueeze(input_tensor, dim)`

  Here, input_tensor is the tensor you want to unsqueeze, and dim is the position where the new dimension will be inserted.

Both `squeeze()` and `unsqueeze()` are essential for shaping tensors in preparation for various operations, such as matrix multiplications, broadcasting, and feeding data into models, ensuring that tensors conform to the expected dimensions.






### Miscellaneous Notes - torch.permute()


In PyTorch, `torch.permute()` is a function used to rearrange the dimensions of a tensor according to a specified order. This allows for complex reshaping and reordering of the data within a tensor, making it a powerful tool for manipulating tensor shapes and dimensions.

---

How `torch.permute()` Works

* Purpose: To reorder the dimensions of a tensor.
* Usage: When you want to change the order of axes/dimensions of a tensor. For example, if you have a tensor of shape (2, 3, 4) and you want to change the order of dimensions to make it (3, 4, 2), you can use torch.permute() to achieve this.

---

Syntax and Example
```
import torch

# Creating a tensor of shape (2, 3, 4)
x = torch.randn(2, 3, 4)

# Permute the dimensions
# Here, we want the dimension order to be (1, 2, 0),
# meaning the new shape will be (3, 4, 2)
y = x.permute(1, 2, 0)

print("Original shape:", x.shape)
print("New shape:", y.shape)
```

In the permute(1, 2, 0) call, the arguments represent the new order of the dimensions:

* The first dimension (0) of x becomes the third dimension of y.
* The second dimension (1) of x becomes the first dimension of y.
* The third dimension (2) of x becomes the second dimension of y.

This results in y having a shape of (3, 4, 2), as per the example.

**Key Points**

* `torch.permute()` does not change the data within the tensor; it only changes how the data is organized by rearranging the tensor dimensions.
* It's useful for operations that require specific dimension orders, such as when preparing data for convolutional layers in neural networks, where you might need to permute dimensions to match the expected input shape.

This flexibility makes `torch.permute()` an essential function for tensor manipulation, especially in complex data processing pipelines and neural network operations.