Resource Link: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


In [2]:
#!nvidia-smi

# Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

---

* Scalar (Rank 0 Tensor): A scalar is a single number. In PyTorch, you create a scalar by passing a single value to torch.tensor(). The code creates a scalar with a value of 7. .ndim checks the number of dimensions (which is 0 for a scalar), .shape returns an empty tuple since scalars have no dimensions, and .item() converts the tensor scalar to a standard Python scalar.

* Vector (Rank 1 Tensor): A vector is a 1-dimensional array of numbers. The code creates a vector [7, 7] using torch.tensor(). Here, .ndim returns 1 indicating it's 1-dimensional, and .shape returns (2), meaning the vector has 2 elements.

* Matrix (Rank 2 Tensor): A matrix is a 2-dimensional array of numbers. The example creates a 2x2 matrix with torch.tensor([[7, 8], [9, 10]]). .ndim shows it's 2-dimensional, and .shape returns (2, 2), indicating 2 rows and 2 columns.

* Higher-Dimensional Tensor (Rank 3+ Tensor): Tensors can have three or more dimensions. The provided code creates a tensor with dimensions (1, 3, 3), meaning it contains a 3x3 matrix in a 3-dimensional space. .ndim confirms it's 3-dimensional. The shape is described as having 1 matrix that contains 3 rows and 3 columns each.

This code is a basic introduction to the concept of tensors in PyTorch, demonstrating how to create them and inspect their properties like dimensionality and shape. Understanding these properties is essential for working with data in machine learning and deep learning applications.

---

**Naming Conventions**
* Scalar (dimension = 0) - lower-case $a$
* Vector (dimension = 1) - lower-case $y$
* Matrix (dimension = 2) - upper-case $Q$
* Tensor (dimension ≥ 3) - upper-case $X$

In [3]:
# Scalar (tensor rank 0)
scalar = torch.tensor(7) # A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor

print(scalar)
print(scalar.ndim) # checks how many dimensions does scalar have
print(scalar.shape)
print(scalar.item()) # Get tensor back as Python int


tensor(7)
0
torch.Size([])
7


> The .item() method is specific to tensors that have a single element. Its purpose is to extract the value of that single element as a standard Python number (int or float). It's particularly useful when you're working with tensors that result from some computations, and you want to convert the result into a Python scalar.

> Attempting to use .item() on a tensor with more than one element will result in an error because it's not clear which element should be converted to a Python scalar. The method is designed to ensure that it's only used when there's exactly one element in the tensor, thereby avoiding ambiguous situations.

In [4]:
# Vector (tensor rank 1)
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim) # checks how many dimension does vector have
print(vector.shape) # outputs the shape of the vector, eg 2 by 1.

tensor([7, 7])
1
torch.Size([2])


In [5]:
# Matrix (tensor rank 2)
MATRIX = torch.tensor([[7, 8], [9, 10]])
print(MATRIX)
print(MATRIX.ndim) # checks how many dimension does MATRIX have
print(MATRIX.shape) # outputs the shape of the matrix

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [6]:
# Tensor (tensor rank 3+)
TENSOR = torch.tensor([[[1, 2, 3],   #[ <-- dim=0[ <-- dim=1 [ <-- dim=2 ]]]
                        [4, 5, 6],
                        [6, 7, 8]]])
print(TENSOR)
print(TENSOR.ndim) # checks how many dimension does TENSOR have

print(TENSOR.shape) # outputs the shape of the tensor
                    # torch.Size([1, 3, 3]) means that you have 1x 3 by 3 matrix in this tensor.
                    # torch.Size([dim=0, dim=1, dim=2])
                    # alternatively, dim=0 contains 1 value (matrix), dim=1 contains 3 values (vector), dim=2 contains 3 scalars each.


tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])
3
torch.Size([1, 3, 3])


### Random Tensors

**Why random tensors?**

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Workflow:

> `Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

PyTorch Docs (torch.rand()) url - https://pytorch.org/docs/stable/generated/torch.rand.html


In [7]:
# Create a random tensor of size (4, 3, 4)
random_tensor = torch.rand(4, 3, 4) # can write "touch.rand(size=(4, 3, 4))" // both are acceptable
print(random_tensor)

tensor([[[0.5554, 0.6828, 0.4384, 0.6635],
         [0.2038, 0.4875, 0.1834, 0.6765],
         [0.1811, 0.6372, 0.3412, 0.1397]],

        [[0.1689, 0.5870, 0.9008, 0.7527],
         [0.4221, 0.2517, 0.5669, 0.2428],
         [0.5212, 0.0844, 0.0394, 0.7711]],

        [[0.6227, 0.5156, 0.4681, 0.0493],
         [0.5847, 0.1569, 0.8865, 0.5630],
         [0.2215, 0.0856, 0.9058, 0.1034]],

        [[0.8626, 0.2869, 0.0932, 0.8415],
         [0.6914, 0.3382, 0.8105, 0.2943],
         [0.2828, 0.6869, 0.9676, 0.2427]]])


In [8]:
print(random_tensor.ndim) # checks how many dimension does random_tensor have
print(random_tensor.shape) # outputs the shape of the random_tensor

3
torch.Size([4, 3, 4])


In [9]:
# Create a random tensor with simillar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # alternative is colour channel coming first, eg. size=(3, 224, 224) // both image dimension of 224x224
print(random_image_size_tensor.ndim) # checks dimension of random_image_size_tensor
print(random_image_size_tensor.shape) # outputs shape of random_image_size_tensor

# random tensors are so valuable because neural network starts with random data -> look at data -> update the random numbers -> look at data .....

3
torch.Size([224, 224, 3])


### Zeros and Ones

In [10]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros * random_tensor) # multiply zero tensor with random tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [11]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones)
print(ones * random_tensor) # multiply zero tensor with random tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[[0.5554, 0.6828, 0.4384, 0.6635],
         [0.2038, 0.4875, 0.1834, 0.6765],
         [0.1811, 0.6372, 0.3412, 0.1397]],

        [[0.1689, 0.5870, 0.9008, 0.7527],
         [0.4221, 0.2517, 0.5669, 0.2428],
         [0.5212, 0.0844, 0.0394, 0.7711]],

        [[0.6227, 0.5156, 0.4681, 0.0493],
         [0.5847, 0.1569, 0.8865, 0.5630],
         [0.2215, 0.0856, 0.9058, 0.1034]],

        [[0.8626, 0.2869, 0.0932, 0.8415],
         [0.6914, 0.3382, 0.8105, 0.2943],
         [0.2828, 0.6869, 0.9676, 0.2427]]])


In [12]:
# datatype
print(zeros.dtype)
print(ones.dtype)
print(random_tensor.dtype)

torch.float32
torch.float32
torch.float32


### Creating a Range of Tensors and Tensors-like

PyTorch docs for "torch.arange()" - https://pytorch.org/docs/stable/generated/torch.arange.html

In [13]:
#torch.range(0, 10) # depracated method, use "torch.arange()" instead
one_to_ten = torch.arange(0, 10) # tensor.arange() starts at start_int, ends at end_int - 1.
print(one_to_ten)
one_to_k = torch.arange(start=0, end=1000, step=77)
print(one_to_k)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])


In [14]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten) # this will get you a tensor full of zeros, which is the same shape as the tensor input, ie "one_to_ten"
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype (eg. happens when inconsistent dtype substitution between tensors)
2. Tensors not right shape (eg. happens in matrix multiplication)
3. Tensors not on the right device (eg. device="cpu" vs device="cuda", and device agnostic code)

In [15]:
# Float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], # even if dtype=None, PyTorch will then revert to default datatype
                               dtype=None, # what datatype is the tensor (e.g float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor's operation
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([1., 2., 3.])
torch.float32


In [16]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16) # convert float_32_tensor to float_16_tensor // alternatively, torch.half would also work
print(float_16_tensor)
print(float_16_tensor.dtype) # float_16_tensor is now float 16

tensor([1., 2., 3.], dtype=torch.float16)
torch.float16


In [17]:
# suprisingly no error raised even though discrepancy in dtype; normal behavious, but can be an issue with large neural network,
# but preferably don't use different' dtype
print(float_16_tensor * float_32_tensor) # works even if multipled by torch.long or torch.int32, etc

tensor([1., 4., 9.])


### Getting Information from Tensors (Tensor Attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get a shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [18]:
# Create a test tensor
some_tensor = torch.rand(2, 3, 4)
print(some_tensor)

tensor([[[0.4242, 0.1673, 0.9578, 0.8151],
         [0.4177, 0.5494, 0.7320, 0.6162],
         [0.5046, 0.8309, 0.9762, 0.6178]],

        [[0.2265, 0.2835, 0.0168, 0.2690],
         [0.3226, 0.7447, 0.6768, 0.7670],
         [0.3669, 0.0049, 0.6687, 0.7158]]])


In [19]:
# Find out details about some_tensor
print(f"Datatype of tensor : {some_tensor.dtype }")
print(f"Shape of tensor    : {some_tensor.shape }")  # "some_tensor.shape" and "some_tensor.size()" does the same thing (shape is attribute, .size() is founction)
print(f"Device of tensor   : {some_tensor.device}")

Datatype of tensor : torch.float32
Shape of tensor    : torch.Size([2, 3, 4])
Device of tensor   : cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [20]:
# Create a Tensor
tensor = torch.tensor([1, 2, 3]) # initialised from Python list or array
print(tensor)
print(tensor + 10) # addition
print(tensor - 10) # subtraction
print(tensor * 10) # multiplication
print(tensor / 10) # division

tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [21]:
# Try out PyTorch built-in functions
print(torch.add(tensor, 10)) # addition
print(torch.sub(tensor, 10)) # subtraction
print(torch.mul(tensor, 10)) # multiplication
print(torch.div(tensor, 10)) # division

print(torch.abs(tensor)) # absolute value
print(torch.sqrt(tensor)) # square root
print(torch.exp(tensor)) # exponential

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
tensor([1, 2, 3])
tensor([1.0000, 1.4142, 1.7321])
tensor([ 2.7183,  7.3891, 20.0855])


### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning are:
1. Element-wise multiplication
2. Matrix multiplication (dot product) [dot product and matrix multiplication is used interchangeably]

URL: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Random Note: To multiply a matrix by another matrix, we need to do the "dot product" of rows and columns... (rewatch 3Blue1Brown if recap needed on linear algebra)

---

Regarding anatomy of Matrix, below as an example is a **4x2 matrix**, pay attention that the int*int order of matrix is classified by `_rows_x_columns_`. Use `tensor.shape`, to find the dimensions of the matrix:

`[`

>  `[1, 2],`

>  `[3, 4],`

>  `[5, 6],`

>  `[7, 8]`

`]`

There are 2 main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:

* `(3x2) @ (3x2)` <-- this won't work
* `(2x3) @ (3x2)` <-- this will work
* `(3x2) @ (2x2)` <-- this will work

2. The resulting matrix has the shape of the **outer dimension**:

* `(4x3) @ (3x6) = (4x6)` <-- 4x6 matrix outputted
* `(3x1) @ (1x7) = (3x7)` <-- 3x7 matrix outputted


> Note: regarding matrix multiplication syntax, `tensor @ tensor`, is the same as `torch.matmul(tensor, tensor)`, same performance wise etc, the '@' operator is an overload of the \__matmul__ magic method in the PyTorch's tensor class.


In [22]:
# Element-wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

print(torch.rand(4, 2).shape) # outputs the shape of a 4x2 matrix
print((torch.rand(4, 3) @ torch.rand(3, 6)).shape) # 4x3 @ 3x6 -> 4x6
print((torch.rand(3, 1) @ torch.rand(1, 7)).shape) # 3x1 @ 1x7 -> 3x7

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
torch.Size([4, 2])
torch.Size([4, 6])
torch.Size([3, 7])


In [23]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [24]:
%%time
value=0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.19 ms, sys: 0 ns, total: 2.19 ms
Wall time: 2.24 ms


In [25]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 108 µs, sys: 0 ns, total: 108 µs
Wall time: 114 µs


tensor(14)

### One of the Most Common Errors in Deep Learning: Shape Errors



In [26]:
# Shapes for Matrix Multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10, 1],
                         [8, 11, 2]])

#torch.mm(tensor_A, tensor_B)  # torch.mm() is the same as torch.matmul() // It's an Alias.
torch.matmul(tensor_A, tensor_B) # As see, need to be 3x2 @ 2x3, which is multipliable. Which this outputs 3x3

tensor([[ 23,  32,   5],
        [ 53,  74,  11],
        [ 83, 116,  17]])

A way to fix our tensor shape issues, is that we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [27]:
print("Original Shape:", tensor_A.shape)
print("Transposed Shape:", tensor_A.T.shape)

Original Shape: torch.Size([3, 2])
Transposed Shape: torch.Size([2, 3])


### Finding the min, max, mean, sum, etc. (Tensor Aggregation)

Definition of "Aggregation": The formation of a number of things into a cluster.


In [28]:
# Create a Tensor

x = torch.arange(0, 100, 10)
print(x)

print(torch.min(x), x.min()) # Find the Min
print(torch.max(x), x.max()) # Find the Max
print(torch.mean(x.float()), x.type(torch.float32).mean()) # Find the Mean // When calculating mean, needs to be in float or complex dtype. Long doesn't work. Refer to MISC.
print(torch.sum(x), x.sum()) # Find the Sum


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) tensor(0)
tensor(90) tensor(90)
tensor(45.) tensor(45.)
tensor(450) tensor(450)


### Finding the Positional min and max

In [29]:
print(x) # outputs "tensor.arange(0, 100, 10)"

# Find the position in tensor that has the minimum value with "argmin()" -> returns index position of target tensor where the minimum value occurs
print(x.argmin(), x[x.argmin()])

# Find the position in tensor that has the maximum value with "argmax()" -> returns index position of target tensor where the maximum value occurs
print(x.argmax(), x[x.argmax()])

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) tensor(0)
tensor(9) tensor(90)


### Reshaping, Stacking, Squeezing and Unsqueezing Tensors

* Reshaping - Reshapes an input tensor to a defined shape, eg 1x12 matrix to a 2x6 matrix of a 4x3 matrix
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [30]:
x = torch.arange(0., 12.)
print(x, x.shape)

# Add an Extra Dimension -- tensor.reshape()
x_reshaped = x.reshape(2, 6)  # reshaping to 2x6 matrix
print(x_reshaped, x_reshaped.shape)

x_reshaped = x.reshape(4, 3)  # reshaping to 4x3 matrix
print(x_reshaped, x_reshaped.shape)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]) torch.Size([12])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]) torch.Size([2, 6])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]]) torch.Size([4, 3])


In [33]:
newTensor = torch.arange(0., 12.)

# Change the View -- tensor.view()
tempView = newTensor.view(2, 6)
print(tempView, tempView.shape)

#Changing "tempView" tensor variable, changes "x" tensor variable (because a view of a tensor shares the same memory as the original input)
tempView[:, 3] = 100  # refer to MISC regarding slicing
print("\n", tempView)
print(newTensor)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]) torch.Size([2, 6])

 tensor([[  0.,   1.,   2., 100.,   4.,   5.],
        [  6.,   7.,   8., 100.,  10.,  11.]])
tensor([  0.,   1.,   2., 100.,   4.,   5.,   6.,   7.,   8., 100.,  10.,  11.])


###Miscellaneous Notes - Image Tensor

**GPT Prompt:** In tensor-speak (the language used to describe tensors), the tensor would have three dimensions, one for colour_channels, height and width.

<br>

**GPT Answer:**

The quote you've provided talks about how to describe the structure of a tensor, particularly in the context of image data, using the specific terminology or "language" associated with tensors.

In the realm of machine learning and computer vision, images are commonly represented as tensors. A tensor, in this context, is essentially a multi-dimensional array. For an image, these dimensions correspond to different aspects of the data it contains:

Color Channels: The number of channels in an image represents the depth of color information. For instance, a standard RGB (Red, Green, Blue) image has three color channels. Each channel stores intensity values for its respective color across the image. There are also grayscale images, which have just one channel, and other formats that may have more channels (like RGBA, where the A stands for Alpha or transparency).

Height: This dimension represents the vertical size of the image in pixels.

Width: This dimension represents the horizontal size of the image in pixels.

So, when the quote mentions a tensor having "three dimensions, one for color_channels, height, and width," it's describing how an image is structured in a way that's understood by tensor operations. For a color image in the RGB format, you could conceptualize it as a 3D tensor:

The first dimension corresponds to the color channels (3 for RGB).
The second dimension corresponds to the height of the image in pixels.
The third dimension corresponds to the width of the image in pixels.
Thus, if you have a 1080x1920 pixel RGB image, in tensor-speak, you would describe it as having dimensions of 3x1080x1920, where 3 represents the RGB channels, 1080 represents the height, and 1920 represents the width.

Understanding this terminology is crucial for working with image data in machine learning frameworks like TensorFlow or PyTorch, as it affects how you process, manipulate, and train models with image data.

<br>
---
<br>

Here's an example of what a tensor array for a 10x10 image with RGBA channels might look like. Each entry in this array is a randomly generated integer between 0 and 255, representing the intensity of the Red, Green, Blue, and Alpha (transparency) channels at each pixel:

---
```
Array shape: (4, 10, 10)

array([[[203, 178,  63, 203,  19,  80,  77,  99, 226, 227], #red
        [148,  31, 141, 150, 187, 184, 214,  10,  40,  95],
        [ 96,  76, 213, 117,  79, 224, 174,  44,   7, 236],
        [182,  25, 242, 120, 207, 194,  52,  38,  42, 222],
        [105, 193, 169, 146, 221,  76, 179,  84, 109, 222],
        [  4, 105,  73,  54, 242, 172, 238,  23,  89, 192],
        [ 79,  26,  75, 133,  92,  10, 115, 114,  87, 227],
        [124, 183,  36, 176, 115, 246, 151, 227,  54,   1],
        [  8, 255, 102, 242, 116,  93,  10, 184, 184,   1],
        [161, 118,  98, 150,  89, 208,  76,  77,  58, 136]],

       [[171, 231, 224, 128, 149, 101,  72, 167,  57, 178], #green
        [170,   3, 175, 194, 243,  77, 188,  97, 197, 206],
        [250, 197,  22, 191, 215, 156,  73,  38, 196,  34],
        [255, 164, 187,  28, 114, 140,  65, 162,  74, 168],
        [212, 127, 120, 162,  86,  22, 141, 126,  81, 167],
        [168, 201,  21, 219, 148,  70, 102, 206, 111, 214],
        [ 23, 204, 152,  56, 164, 110, 197, 213,  28, 206],
        [162, 149, 100, 206,  25,  88, 161,  83, 173, 177],
        [218,  38,  76, 220,  37,  36,  11, 228,   0, 107],
        [ 29,  94, 173, 170,  31, 207, 251,  65, 205,  95]],

       [[ 17, 117, 145,  64, 124,  20, 242, 202, 159,  72], #blue
        [214, 102, 124, 170, 191,  93,  23, 251, 249,  62],
        [ 25, 245, 169, 116, 131,  39,  68, 147,  79,  90],
        [111,  33,  35, 196, 197, 170,  51, 197,  62,  70],
        [ 47,  41, 113, 166, 202,  24, 242, 246,  68, 245],
        [174,   4,  77,  83,  42,  65, 183,  58, 113,  44],
        [221, 117, 252, 153, 119,  45, 137, 104,  58,  57],
        [168, 231, 210, 239,  32,  30,   9, 150,  95, 214],
        [127, 240,  56, 200, 161, 137, 197,   6, 231,  72],
        [  4, 109,  53,  11, 197, 217,  88,   1, 249, 254]],

       [[ 23, 252, 127,   8,  58, 222, 123,   6,  14, 108], #alpha
        [  4, 195,  26, 177,  59, 145, 199, 167, 181,  93],
        [  4, 119, 204, 182, 108,  53, 175, 159,  83,  50],
        [ 47, 233, 103, 198,  84, 134,  42, 145,  93, 235],
        [ 35, 165, 152,  77, 101, 153, 242, 206, 109,   9],
        [ 78, 210, 182, 151,  48, 209, 199,  33, 138,  95],
        [226, 206, 106,  47,  54,  49, 178, 107, 112, 105],
        [195,  17,  24, 144,  91,  14, 102, 123, 246, 231],
        [253, 137,  22, 133,  19, 192, 166,  24, 145,  78],
        [ 69, 165, 135, 255, 122, 125, 135, 160, 174,  54]]], dtype=uint8)
```
---

This representation shows a 4-dimensional tensor where:

* The first dimension corresponds to the color channels (RGBA), so there are 4 layers or slices.
* The second and third dimensions correspond to the height and width of the image, respectively, both set to 10 pixels in this example.

Each "layer" or slice of the tensor represents one of the RGBA channels across the entire image. The values within each layer represent the intensity of that channel for each pixel, with 0 being no intensity (or completely transparent for the alpha channel) and 255 being the maximum intensity. ​​






In Jupyter notebooks, which include Google Colab notebooks, you do not always need to use the print() function to display output. This environment is designed for interactive computing, and it has a feature that automatically displays the result of the last operation in each cell.

When you run a cell in a Jupyter notebook (or Google Colab, which is based on Jupyter), the following rules apply:

The last line of code in a cell, when executed, will have its result displayed below the cell, even if it is not printed with the print() function. This is known as the cell's output.
If the last line of code does not produce any output, nothing is displayed.
If you have other lines of code in the cell whose output you wish to display, you need to explicitly use print() or another display function for those lines.
This feature is especially useful for quick data exploration and analysis, as it allows you to see the results immediately without needing to use print() every time. However, if you want to format the output or display multiple outputs within a cell, you'll need to use print() or another suitable display function.

**Notes Regarding Why you don't need to declare print() to output value in Google Colab**

<br>

In Jupyter notebooks, which include Google Colab notebooks, you do not always need to use the $print()$ function to display output. This environment is designed for interactive computing, and it has a feature that automatically displays the result of the last operation in each cell.

When you run a cell in a Jupyter notebook (or Google Colab, which is based on Jupyter), the following rules apply:

1. The last line of code in a cell, when executed, will have its result displayed below the cell, even if it is not printed with the $print()$ function. This is known as the cell's output.
2. If the last line of code does not produce any output, nothing is displayed.
3. If you have other lines of code in the cell whose output you wish to display, you need to explicitly use $print()$ or another display function for those lines.


This feature is especially useful for quick data exploration and analysis, as it allows you to see the results immediately without needing to use $print()$ every time. However, if you want to format the output or display multiple outputs within a cell, you'll need to use $print()$ or another suitable display function.

### Miscellaneous Notes - Dimensions

**GPT Prompt**: what even is ndim in torch, as in, what is dimension of tensors even. as scalars are normally assosciated with the number line 1st dimension, however here it is assosicated with the 0th dimension. can i know why does tensorflow consider scalar as 0th, vector as 1st, matrix 2nd etc

<br>

**GPT Answer**:

The concept of dimensionality in tensors (as used in libraries like PyTorch and TensorFlow) is rooted in the mathematical definition of dimensions in linear algebra, but it's also slightly adapted to fit programming and data structure paradigms.

**Understanding Dimensions**

* Dimensionality: In the context of tensors, the dimensionality (or rank) refers to the number of indices required to uniquely select each element of the tensor. This concept is directly tied to how data can be organized and represented in structured forms:
> * A scalar can be thought of as a single number. It doesn't contain any axes (or directions), so it's considered 0-dimensional. You don't need any index to access it because it's just a single value.
> * A vector is a 1-dimensional array. You need one index to access each element. Think of it as a line where each element can be located at a certain position along that line.
> * A matrix is a 2-dimensional array. You need two indices to access each element (one for the row and one for the column). It can be visualized as a plane or grid where positions are defined by two coordinates.
> * Higher-dimensional tensors (3D, 4D, etc.) require more indices to access each element and represent more complex structures (like a cube for a 3D tensor).

**Why Scalars are Considered 0-Dimensional**

The designation of scalars as 0-dimensional in libraries like TensorFlow and PyTorch is consistent with how dimensions are mathematically defined. Since a scalar does not require any indices to access (it's just a single value), it is considered 0-dimensional. This definition helps maintain consistency across mathematical theory and its implementation in programming:

* It aligns with the mathematical concept of a dimension as the number of coordinates needed to specify a point within it.
* It provides a basis for defining operations and transformations on tensors in a way that is consistent regardless of their rank.

**Practical Implications**

This conceptual framework has practical implications in programming and data processing:

* Generalization: By defining a scalar as a 0-dimensional tensor, vectors as 1-dimensional, matrices as 2-dimensional, and so on, libraries can offer a unified and consistent API for tensor operations that works across tensors of any dimensionality.
* Broadcasting and Shape Manipulation: Understanding dimensionality is crucial for operations that involve multiple tensors, especially when their shapes differ. It allows for the implementation of broadcasting rules, where tensors of different shapes are used together in operations.
* Data Representation: This hierarchical structure (scalar < vector < matrix < tensor) provides an intuitive way to represent increasingly complex data. For instance, a 3D tensor could represent a sequence of images (2D tensors), where each image is a matrix of pixel values.

In summary, the classification of scalars as 0-dimensional and so on up the hierarchy to higher-dimensional tensors is a logical extension of mathematical principles into programming constructs, allowing for more versatile and powerful data manipulation capabilities in libraries like PyTorch and TensorFlow.

### Miscellaneous Notes - tensor.mean() Dtype 'Long' issue

**GPT Prompt:** Why does long not work with .mean() in PyTorch

**GPT Answer:** In PyTorch, the .mean() operation computes the arithmetic mean of all the elements in the tensor. For the mean to be meaningful, especially in the context of floating-point arithmetic, the operation is defined only for tensors with floating point or complex numbers. This is because the mean is not always an integer value, and rounding to an integer could lead to loss of precision and incorrect calculations in subsequent operations.

The tensor you are working with has been created with the default integer type (torch.int64 or Long type in PyTorch), as inferred from the torch.arange function. To calculate the mean, you need to first convert it to a floating-point type. You can do this by using the .float() or .to() methods on the tensor.

Here's how you can modify your tensor to compute the mean:

```
x_float = x.float()  # Convert x to a float tensor
print(torch.mean(x_float), x_float.mean())  # Now you can compute the mean
```

This converts the tensor x to a floating point tensor (torch.float32), which allows the .mean() method to work correctly.

### Miscellaneous Notes - Regarding Slicing [:] in Python

**GPT Answer Regarding Slicing[:] in Python**
In Python, slicing is a feature that allows you to access a portion of a sequence type (like lists, strings, tuples) or array-like objects (like NumPy arrays and PyTorch tensors). The slicing operator [:] is used to access elements of an iterable based on their indices. Here are some examples of how slicing works:

---

**Lists**

* Let's start with a simple list:
> `my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`
* Accessing all elements:
> `all_elements = my_list[:]  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`
* Accessing the first 5 elements:
> `first_five = my_list[:5]  # [0, 1, 2, 3, 4]`
* Accessing elements from index 5 to the end:
> `from_five_onwards = my_list[5:]  # [5, 6, 7, 8, 9]`
* Accessing elements from index 3 to 7 (not including 7):
> `subset = my_list[3:7]  # [3, 4, 5, 6]`
* Accessing elements with a step (every second element):
> `every_second = my_list[::2]  # [0, 2, 4, 6, 8]`
* Accessing elements in reverse:
> `reversed_list = my_list[::-1]  # [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]`

---

**Strings**

* Slicing works similarly with strings:
> `my_string = "Hello, World!"`

* Accessing all characters:
> `all_chars = my_string[:]  # "Hello, World!"`

* Accessing the first 5 characters:
> `first_five = my_string[:5]  # "Hello"`

* Accessing characters from index 7 to the end:
> `from_seven_onwards = my_string[7:]  # "World!"`

---

**NumPy Arrays**

* For NumPy arrays (and similarly for PyTorch tensors), slicing can be multidimensional:

> ```
import numpy as np
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
> ```

* Accessing the entire array:
> `all_elements = my_array[:]  # array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`

* Accessing the first two rows:
> `first_two_rows = my_array[:2]  # array([[1, 2, 3], [4, 5, 6]])`

* Accessing the second column:
> `second_column = my_array[:, 1]  # array([2, 5, 8])`

Accessing a submatrix (first two rows, last two columns):
> `submatrix = my_array[:2, 1:]  # array([[2, 3], [5, 6]])`

---

Slicing is a powerful tool in Python that lets you retrieve elements efficiently from sequences and array-like objects without the need for explicit loops.